# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.4
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_pyktlib', [dirname(__file__)])
        except ImportError:
            import _pyktlib
            return _pyktlib
        if fp is not None:
            try:
                _mod = imp.load_module('_pyktlib', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _pyktlib = swig_import_helper()
    del swig_import_helper
else:
    import _pyktlib
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _pyktlib.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _pyktlib.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _pyktlib.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _pyktlib.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _pyktlib.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _pyktlib.SwigPyIterator_equal(self, x)

    def copy(self):
        return _pyktlib.SwigPyIterator_copy(self)

    def next(self):
        return _pyktlib.SwigPyIterator_next(self)

    def __next__(self):
        return _pyktlib.SwigPyIterator___next__(self)

    def previous(self):
        return _pyktlib.SwigPyIterator_previous(self)

    def advance(self, n):
        return _pyktlib.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _pyktlib.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _pyktlib.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _pyktlib.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _pyktlib.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _pyktlib.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _pyktlib.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _pyktlib.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)


def BlackPrice(F, K, vol, t_exp, df, PutCall):
    return _pyktlib.BlackPrice(F, K, vol, t_exp, df, PutCall)
BlackPrice = _pyktlib.BlackPrice

def BlackScholesPrice(S, K, vol, t_exp, rf, rd, PutCall):
    return _pyktlib.BlackScholesPrice(S, K, vol, t_exp, rf, rd, PutCall)
BlackScholesPrice = _pyktlib.BlackScholesPrice

def BlackDelta(F, K, vol, t_exp, df, PutCall):
    return _pyktlib.BlackDelta(F, K, vol, t_exp, df, PutCall)
BlackDelta = _pyktlib.BlackDelta

def BSDigitalPrice(F, K, vol, t_exp, df, PutCall):
    return _pyktlib.BSDigitalPrice(F, K, vol, t_exp, df, PutCall)
BSDigitalPrice = _pyktlib.BSDigitalPrice

def BachelierPrice(F, K, vol, t_exp, df, PutCall):
    return _pyktlib.BachelierPrice(F, K, vol, t_exp, df, PutCall)
BachelierPrice = _pyktlib.BachelierPrice

def BlackImpliedVol(MktPrice, F, K, r, T, PutCall):
    return _pyktlib.BlackImpliedVol(MktPrice, F, K, r, T, PutCall)
BlackImpliedVol = _pyktlib.BlackImpliedVol

def BachelierImpliedVol(MktPrice, F, K, r, T, PutCall):
    return _pyktlib.BachelierImpliedVol(MktPrice, F, K, r, T, PutCall)
BachelierImpliedVol = _pyktlib.BachelierImpliedVol

def american_prem_fut_btree(F, K, vol, t_exp, df, PutCall):
    return _pyktlib.american_prem_fut_btree(F, K, vol, t_exp, df, PutCall)
american_prem_fut_btree = _pyktlib.american_prem_fut_btree

def AmericanOptFutPrice(F, K, vol, t_exp, df, PutCall):
    return _pyktlib.AmericanOptFutPrice(F, K, vol, t_exp, df, PutCall)
AmericanOptFutPrice = _pyktlib.AmericanOptFutPrice

def AmericanImpliedVol(MktPrice, F, K, r, T, PutCall):
    return _pyktlib.AmericanImpliedVol(MktPrice, F, K, r, T, PutCall)
AmericanImpliedVol = _pyktlib.AmericanImpliedVol

def SamuelsonFactor(a, b, t, T, mat):
    return _pyktlib.SamuelsonFactor(a, b, t, T, mat)
SamuelsonFactor = _pyktlib.SamuelsonFactor
class VolNode(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VolNode, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VolNode, name)
    __repr__ = _swig_repr

    def GetVolByStrike(self, strike, dmat=0):
        return _pyktlib.VolNode_GetVolByStrike(self, strike, dmat)

    def GetVolByDelta(self, delta, dmat=0):
        return _pyktlib.VolNode_GetVolByDelta(self, delta, dmat)

    def GetVolByMoneyness(self, ratio, dmat=0):
        return _pyktlib.VolNode_GetVolByMoneyness(self, ratio, dmat)

    def GetInstVol(self, d=0):
        return _pyktlib.VolNode_GetInstVol(self, d)

    def setAtm(self, atm):
        return _pyktlib.VolNode_setAtm(self, atm)

    def setToday(self, dtoday):
        return _pyktlib.VolNode_setToday(self, dtoday)

    def setExp(self, dexp):
        return _pyktlib.VolNode_setExp(self, dexp)

    def atmVol_(self):
        return _pyktlib.VolNode_atmVol_(self)

    def dtoday_(self):
        return _pyktlib.VolNode_dtoday_(self)

    def dexp_(self):
        return _pyktlib.VolNode_dexp_(self)

    def expiry_(self):
        return _pyktlib.VolNode_expiry_(self)

    def __init__(self, *args):
        this = _pyktlib.new_VolNode(*args)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _pyktlib.delete_VolNode
    __del__ = lambda self: None
VolNode_swigregister = _pyktlib.VolNode_swigregister
VolNode_swigregister(VolNode)

class SamuelVolNode(VolNode):
    __swig_setmethods__ = {}
    for _s in [VolNode]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, SamuelVolNode, name, value)
    __swig_getmethods__ = {}
    for _s in [VolNode]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, SamuelVolNode, name)
    __repr__ = _swig_repr

    def __init__(self, dtoday, dexp, atm, alpha, beta):
        this = _pyktlib.new_SamuelVolNode(dtoday, dexp, atm, alpha, beta)
        try:
            self.this.append(this)
        except:
            self.this = this

    def alpha_(self):
        return _pyktlib.SamuelVolNode_alpha_(self)

    def beta_(self):
        return _pyktlib.SamuelVolNode_beta_(self)

    def setAlpha(self, alpha):
        return _pyktlib.SamuelVolNode_setAlpha(self, alpha)

    def setBeta(self, beta):
        return _pyktlib.SamuelVolNode_setBeta(self, beta)

    def GetVolByMoneyness(self, ratio, dmat):
        return _pyktlib.SamuelVolNode_GetVolByMoneyness(self, ratio, dmat)

    def GetInstVol(self, d):
        return _pyktlib.SamuelVolNode_GetInstVol(self, d)
    __swig_destroy__ = _pyktlib.delete_SamuelVolNode
    __del__ = lambda self: None
SamuelVolNode_swigregister = _pyktlib.SamuelVolNode_swigregister
SamuelVolNode_swigregister(SamuelVolNode)

class Delta5VolNode(VolNode):
    __swig_setmethods__ = {}
    for _s in [VolNode]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Delta5VolNode, name, value)
    __swig_getmethods__ = {}
    for _s in [VolNode]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, Delta5VolNode, name)
    __repr__ = _swig_repr

    def __init__(self, dtoday, dexp, fwd, atm, v90, v75, v25, v10, omega):
        this = _pyktlib.new_Delta5VolNode(dtoday, dexp, fwd, atm, v90, v75, v25, v10, omega)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _pyktlib.delete_Delta5VolNode
    __del__ = lambda self: None

    def initialize(self):
        return _pyktlib.Delta5VolNode_initialize(self)

    def setAtm(self, atm):
        return _pyktlib.Delta5VolNode_setAtm(self, atm)

    def setD10Vol(self, d10Vol):
        return _pyktlib.Delta5VolNode_setD10Vol(self, d10Vol)

    def setD25Vol(self, d25Vol):
        return _pyktlib.Delta5VolNode_setD25Vol(self, d25Vol)

    def setD75Vol(self, d75Vol):
        return _pyktlib.Delta5VolNode_setD75Vol(self, d75Vol)

    def setD90Vol(self, d90Vol):
        return _pyktlib.Delta5VolNode_setD90Vol(self, d90Vol)

    def d10Vol_(self):
        return _pyktlib.Delta5VolNode_d10Vol_(self)

    def d25Vol_(self):
        return _pyktlib.Delta5VolNode_d25Vol_(self)

    def d75Vol_(self):
        return _pyktlib.Delta5VolNode_d75Vol_(self)

    def d90Vol_(self):
        return _pyktlib.Delta5VolNode_d90Vol_(self)

    def fwd_(self):
        return _pyktlib.Delta5VolNode_fwd_(self)

    def omega_(self):
        return _pyktlib.Delta5VolNode_omega_(self)

    def GetVolByStrike(self, strike, dmat=0):
        return _pyktlib.Delta5VolNode_GetVolByStrike(self, strike, dmat)

    def GetVolByDelta(self, delta, dmat=0):
        return _pyktlib.Delta5VolNode_GetVolByDelta(self, delta, dmat)

    def GetVolByMoneyness(self, ratio, dmat=0):
        return _pyktlib.Delta5VolNode_GetVolByMoneyness(self, ratio, dmat)
Delta5VolNode_swigregister = _pyktlib.Delta5VolNode_swigregister
Delta5VolNode_swigregister(Delta5VolNode)

class SamuelDelta5VolNode(Delta5VolNode):
    __swig_setmethods__ = {}
    for _s in [Delta5VolNode]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, SamuelDelta5VolNode, name, value)
    __swig_getmethods__ = {}
    for _s in [Delta5VolNode]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, SamuelDelta5VolNode, name)
    __repr__ = _swig_repr

    def __init__(self, dtoday, dexp, fwd, atm, v90, v75, v25, v10, alpha, beta, omega):
        this = _pyktlib.new_SamuelDelta5VolNode(dtoday, dexp, fwd, atm, v90, v75, v25, v10, alpha, beta, omega)
        try:
            self.this.append(this)
        except:
            self.this = this

    def alpha_(self):
        return _pyktlib.SamuelDelta5VolNode_alpha_(self)

    def beta_(self):
        return _pyktlib.SamuelDelta5VolNode_beta_(self)

    def setAlpha(self, alpha):
        return _pyktlib.SamuelDelta5VolNode_setAlpha(self, alpha)

    def setBeta(self, beta):
        return _pyktlib.SamuelDelta5VolNode_setBeta(self, beta)

    def GetVolByMoneyness(self, ratio, dmat):
        return _pyktlib.SamuelDelta5VolNode_GetVolByMoneyness(self, ratio, dmat)

    def GetInstVol(self, d):
        return _pyktlib.SamuelDelta5VolNode_GetInstVol(self, d)
    __swig_destroy__ = _pyktlib.delete_SamuelDelta5VolNode
    __del__ = lambda self: None
SamuelDelta5VolNode_swigregister = _pyktlib.SamuelDelta5VolNode_swigregister
SamuelDelta5VolNode_swigregister(SamuelDelta5VolNode)

class Pricer(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Pricer, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Pricer, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def price(self):
        return _pyktlib.Pricer_price(self)

    def delta(self):
        return _pyktlib.Pricer_delta(self)

    def gamma(self):
        return _pyktlib.Pricer_gamma(self)

    def vega(self):
        return _pyktlib.Pricer_vega(self)

    def theta(self):
        return _pyktlib.Pricer_theta(self)

    def setStrike(self, strike):
        return _pyktlib.Pricer_setStrike(self, strike)

    def setFwd(self, fwd):
        return _pyktlib.Pricer_setFwd(self, fwd)

    def setVol(self, vol):
        return _pyktlib.Pricer_setVol(self, vol)

    def setIR(self, ir):
        return _pyktlib.Pricer_setIR(self, ir)

    def setExpiry(self, dexp):
        return _pyktlib.Pricer_setExpiry(self, dexp)

    def setToday(self, dtoday):
        return _pyktlib.Pricer_setToday(self, dtoday)

    def setOtype(self, otype):
        return _pyktlib.Pricer_setOtype(self, otype)

    def strike_(self):
        return _pyktlib.Pricer_strike_(self)

    def fwd_(self):
        return _pyktlib.Pricer_fwd_(self)

    def vol_(self):
        return _pyktlib.Pricer_vol_(self)

    def dexp_(self):
        return _pyktlib.Pricer_dexp_(self)

    def dtoday_(self):
        return _pyktlib.Pricer_dtoday_(self)

    def irate_(self):
        return _pyktlib.Pricer_irate_(self)

    def otype_(self):
        return _pyktlib.Pricer_otype_(self)

    def priceTweak(self):
        return _pyktlib.Pricer_priceTweak(self)

    def volTweak(self):
        return _pyktlib.Pricer_volTweak(self)
    __swig_destroy__ = _pyktlib.delete_Pricer
    __del__ = lambda self: None
Pricer_swigregister = _pyktlib.Pricer_swigregister
Pricer_swigregister(Pricer)

class BlackPricer(Pricer):
    __swig_setmethods__ = {}
    for _s in [Pricer]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, BlackPricer, name, value)
    __swig_getmethods__ = {}
    for _s in [Pricer]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, BlackPricer, name)
    __repr__ = _swig_repr

    def __init__(self, dtoday, dexp, fwd, vol, strike, ir, otype):
        this = _pyktlib.new_BlackPricer(dtoday, dexp, fwd, vol, strike, ir, otype)
        try:
            self.this.append(this)
        except:
            self.this = this

    def price(self):
        return _pyktlib.BlackPricer_price(self)
    __swig_destroy__ = _pyktlib.delete_BlackPricer
    __del__ = lambda self: None
BlackPricer_swigregister = _pyktlib.BlackPricer_swigregister
BlackPricer_swigregister(BlackPricer)

class AmericanFutPricer(Pricer):
    __swig_setmethods__ = {}
    for _s in [Pricer]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, AmericanFutPricer, name, value)
    __swig_getmethods__ = {}
    for _s in [Pricer]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, AmericanFutPricer, name)
    __repr__ = _swig_repr

    def __init__(self, dtoday, dexp, fwd, vol, strike, ir, otype):
        this = _pyktlib.new_AmericanFutPricer(dtoday, dexp, fwd, vol, strike, ir, otype)
        try:
            self.this.append(this)
        except:
            self.this = this

    def price(self):
        return _pyktlib.AmericanFutPricer_price(self)
    __swig_destroy__ = _pyktlib.delete_AmericanFutPricer
    __del__ = lambda self: None
AmericanFutPricer_swigregister = _pyktlib.AmericanFutPricer_swigregister
AmericanFutPricer_swigregister(AmericanFutPricer)

class DigitalPricer(Pricer):
    __swig_setmethods__ = {}
    for _s in [Pricer]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, DigitalPricer, name, value)
    __swig_getmethods__ = {}
    for _s in [Pricer]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, DigitalPricer, name)
    __repr__ = _swig_repr

    def __init__(self, dtoday, dexp, fwd, vol, strike, ir, otype):
        this = _pyktlib.new_DigitalPricer(dtoday, dexp, fwd, vol, strike, ir, otype)
        try:
            self.this.append(this)
        except:
            self.this = this

    def price(self):
        return _pyktlib.DigitalPricer_price(self)
    __swig_destroy__ = _pyktlib.delete_DigitalPricer
    __del__ = lambda self: None
DigitalPricer_swigregister = _pyktlib.DigitalPricer_swigregister
DigitalPricer_swigregister(DigitalPricer)

class BachelierPricer(Pricer):
    __swig_setmethods__ = {}
    for _s in [Pricer]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, BachelierPricer, name, value)
    __swig_getmethods__ = {}
    for _s in [Pricer]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, BachelierPricer, name)
    __repr__ = _swig_repr

    def __init__(self, dtoday, dexp, fwd, vol, strike, ir, otype):
        this = _pyktlib.new_BachelierPricer(dtoday, dexp, fwd, vol, strike, ir, otype)
        try:
            self.this.append(this)
        except:
            self.this = this

    def price(self):
        return _pyktlib.BachelierPricer_price(self)
    __swig_destroy__ = _pyktlib.delete_BachelierPricer
    __del__ = lambda self: None
BachelierPricer_swigregister = _pyktlib.BachelierPricer_swigregister
BachelierPricer_swigregister(BachelierPricer)

class BlackStripPricer(Pricer):
    __swig_setmethods__ = {}
    for _s in [Pricer]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, BlackStripPricer, name, value)
    __swig_getmethods__ = {}
    for _s in [Pricer]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, BlackStripPricer, name)
    __repr__ = _swig_repr

    def __init__(self, dtoday, startDate, endDate, fwd, vol, strike, ir, otype, hols):
        this = _pyktlib.new_BlackStripPricer(dtoday, startDate, endDate, fwd, vol, strike, ir, otype, hols)
        try:
            self.this.append(this)
        except:
            self.this = this

    def price(self):
        return _pyktlib.BlackStripPricer_price(self)

    def setFwd(self, fwd):
        return _pyktlib.BlackStripPricer_setFwd(self, fwd)

    def setVol(self, vol):
        return _pyktlib.BlackStripPricer_setVol(self, vol)

    def setIR(self, ir):
        return _pyktlib.BlackStripPricer_setIR(self, ir)

    def setToday(self, dtoday):
        return _pyktlib.BlackStripPricer_setToday(self, dtoday)
    __swig_destroy__ = _pyktlib.delete_BlackStripPricer
    __del__ = lambda self: None
BlackStripPricer_swigregister = _pyktlib.BlackStripPricer_swigregister
BlackStripPricer_swigregister(BlackStripPricer)

class DigitalStripPricer(Pricer):
    __swig_setmethods__ = {}
    for _s in [Pricer]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, DigitalStripPricer, name, value)
    __swig_getmethods__ = {}
    for _s in [Pricer]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, DigitalStripPricer, name)
    __repr__ = _swig_repr

    def __init__(self, dtoday, startDate, endDate, fwd, vol, strike, ir, otype, hols):
        this = _pyktlib.new_DigitalStripPricer(dtoday, startDate, endDate, fwd, vol, strike, ir, otype, hols)
        try:
            self.this.append(this)
        except:
            self.this = this

    def price(self):
        return _pyktlib.DigitalStripPricer_price(self)

    def setFwd(self, fwd):
        return _pyktlib.DigitalStripPricer_setFwd(self, fwd)

    def setVol(self, vol):
        return _pyktlib.DigitalStripPricer_setVol(self, vol)

    def setIR(self, ir):
        return _pyktlib.DigitalStripPricer_setIR(self, ir)

    def setToday(self, dtoday):
        return _pyktlib.DigitalStripPricer_setToday(self, dtoday)
    __swig_destroy__ = _pyktlib.delete_DigitalStripPricer
    __del__ = lambda self: None
DigitalStripPricer_swigregister = _pyktlib.DigitalStripPricer_swigregister
DigitalStripPricer_swigregister(DigitalStripPricer)

class BarrierPricer(Pricer):
    __swig_setmethods__ = {}
    for _s in [Pricer]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, BarrierPricer, name, value)
    __swig_getmethods__ = {}
    for _s in [Pricer]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, BarrierPricer, name)
    __repr__ = _swig_repr

    def __init__(self, dtoday, dexp, fwd, vol, strike, barrier, btype, ir, otype, mtype):
        this = _pyktlib.new_BarrierPricer(dtoday, dexp, fwd, vol, strike, barrier, btype, ir, otype, mtype)
        try:
            self.this.append(this)
        except:
            self.this = this

    def price(self):
        return _pyktlib.BarrierPricer_price(self)

    def setBarrier(self, barrier):
        return _pyktlib.BarrierPricer_setBarrier(self, barrier)

    def setBtype(self, btype):
        return _pyktlib.BarrierPricer_setBtype(self, btype)

    def setMtype(self, mtype):
        return _pyktlib.BarrierPricer_setMtype(self, mtype)

    def barrier_(self):
        return _pyktlib.BarrierPricer_barrier_(self)

    def btype_(self):
        return _pyktlib.BarrierPricer_btype_(self)

    def mtype_(self):
        return _pyktlib.BarrierPricer_mtype_(self)
    __swig_destroy__ = _pyktlib.delete_BarrierPricer
    __del__ = lambda self: None
BarrierPricer_swigregister = _pyktlib.BarrierPricer_swigregister
BarrierPricer_swigregister(BarrierPricer)

class BarrierStripPricer(Pricer):
    __swig_setmethods__ = {}
    for _s in [Pricer]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, BarrierStripPricer, name, value)
    __swig_getmethods__ = {}
    for _s in [Pricer]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, BarrierStripPricer, name)
    __repr__ = _swig_repr

    def __init__(self, dtoday, startDate, endDate, fwd, vol, strike, barrier, btype, ir, otype, mtype, hols):
        this = _pyktlib.new_BarrierStripPricer(dtoday, startDate, endDate, fwd, vol, strike, barrier, btype, ir, otype, mtype, hols)
        try:
            self.this.append(this)
        except:
            self.this = this

    def price(self):
        return _pyktlib.BarrierStripPricer_price(self)

    def setFwd(self, fwd):
        return _pyktlib.BarrierStripPricer_setFwd(self, fwd)

    def setVol(self, vol):
        return _pyktlib.BarrierStripPricer_setVol(self, vol)

    def setIR(self, ir):
        return _pyktlib.BarrierStripPricer_setIR(self, ir)

    def setToday(self, dtoday):
        return _pyktlib.BarrierStripPricer_setToday(self, dtoday)

    def setBarrier(self, barrier):
        return _pyktlib.BarrierStripPricer_setBarrier(self, barrier)

    def setBtype(self, btype):
        return _pyktlib.BarrierStripPricer_setBtype(self, btype)

    def setMtype(self, mtype):
        return _pyktlib.BarrierStripPricer_setMtype(self, mtype)

    def barrier_(self):
        return _pyktlib.BarrierStripPricer_barrier_(self)

    def btype_(self):
        return _pyktlib.BarrierStripPricer_btype_(self)

    def mtype_(self):
        return _pyktlib.BarrierStripPricer_mtype_(self)
    __swig_destroy__ = _pyktlib.delete_BarrierStripPricer
    __del__ = lambda self: None
BarrierStripPricer_swigregister = _pyktlib.BarrierStripPricer_swigregister
BarrierStripPricer_swigregister(BarrierStripPricer)

class MCBarrierPricer(BarrierPricer):
    __swig_setmethods__ = {}
    for _s in [BarrierPricer]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, MCBarrierPricer, name, value)
    __swig_getmethods__ = {}
    for _s in [BarrierPricer]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, MCBarrierPricer, name)
    __repr__ = _swig_repr

    def __init__(self, dtoday, dexp, fwd, vol, strike, barrier, btype, ir, otype, mtype, hols, nPath, useAntithetic):
        this = _pyktlib.new_MCBarrierPricer(dtoday, dexp, fwd, vol, strike, barrier, btype, ir, otype, mtype, hols, nPath, useAntithetic)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _pyktlib.delete_MCBarrierPricer
    __del__ = lambda self: None

    def mc_(self):
        return _pyktlib.MCBarrierPricer_mc_(self)

    def theta(self):
        return _pyktlib.MCBarrierPricer_theta(self)

    def setFwd(self, fwd):
        return _pyktlib.MCBarrierPricer_setFwd(self, fwd)

    def setVol(self, vol):
        return _pyktlib.MCBarrierPricer_setVol(self, vol)

    def setToday(self, dtoday):
        return _pyktlib.MCBarrierPricer_setToday(self, dtoday)

    def price(self):
        return _pyktlib.MCBarrierPricer_price(self)

    def priceTweak(self):
        return _pyktlib.MCBarrierPricer_priceTweak(self)

    def volTweak(self):
        return _pyktlib.MCBarrierPricer_volTweak(self)
MCBarrierPricer_swigregister = _pyktlib.MCBarrierPricer_swigregister
MCBarrierPricer_swigregister(MCBarrierPricer)


def SmileToLognormal(p, stdev, Strikes, CDFs):
    return _pyktlib.SmileToLognormal(p, stdev, Strikes, CDFs)
SmileToLognormal = _pyktlib.SmileToLognormal
class BarrierSmilePricer(BarrierPricer):
    __swig_setmethods__ = {}
    for _s in [BarrierPricer]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, BarrierSmilePricer, name, value)
    __swig_getmethods__ = {}
    for _s in [BarrierPricer]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, BarrierSmilePricer, name)
    __repr__ = _swig_repr

    def __init__(self, dtoday, dexp, fwd, vol, strike, barrier, btype, ir, otype, mtype, nSteps=1600, nSigmas=6.0):
        this = _pyktlib.new_BarrierSmilePricer(dtoday, dexp, fwd, vol, strike, barrier, btype, ir, otype, mtype, nSteps, nSigmas)
        try:
            self.this.append(this)
        except:
            self.this = this

    def price(self):
        return _pyktlib.BarrierSmilePricer_price(self)

    def priceTweak(self):
        return _pyktlib.BarrierSmilePricer_priceTweak(self)

    def volTweak(self):
        return _pyktlib.BarrierSmilePricer_volTweak(self)
    __swig_destroy__ = _pyktlib.delete_BarrierSmilePricer
    __del__ = lambda self: None
BarrierSmilePricer_swigregister = _pyktlib.BarrierSmilePricer_swigregister
BarrierSmilePricer_swigregister(BarrierSmilePricer)

class TimeSeries(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TimeSeries, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TimeSeries, name)
    __repr__ = _swig_repr

    def date_(self):
        return _pyktlib.TimeSeries_date_(self)

    def data_(self):
        return _pyktlib.TimeSeries_data_(self)

    def __init__(self, *args):
        this = _pyktlib.new_TimeSeries(*args)
        try:
            self.this.append(this)
        except:
            self.this = this

    def setDate(self, date):
        return _pyktlib.TimeSeries_setDate(self, date)

    def setData(self, data):
        return _pyktlib.TimeSeries_setData(self, data)

    def isValidated(self):
        return _pyktlib.TimeSeries_isValidated(self)
    __swig_destroy__ = _pyktlib.delete_TimeSeries
    __del__ = lambda self: None
TimeSeries_swigregister = _pyktlib.TimeSeries_swigregister
TimeSeries_swigregister(TimeSeries)


def GetTSWeightedSum(ts1, ts2, w1, w2):
    return _pyktlib.GetTSWeightedSum(ts1, ts2, w1, w2)
GetTSWeightedSum = _pyktlib.GetTSWeightedSum
class HistVolCalculator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, HistVolCalculator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, HistVolCalculator, name)
    __repr__ = _swig_repr

    def __init__(self, ts, expiry, freq, btMonths):
        this = _pyktlib.new_HistVolCalculator(ts, expiry, freq, btMonths)
        try:
            self.this.append(this)
        except:
            self.this = this

    def pricer(self, fwd, strike, vol, currDate):
        return _pyktlib.HistVolCalculator_pricer(self, fwd, strike, vol, currDate)

    def delta(self, fwd, strike, vol, currDate):
        return _pyktlib.HistVolCalculator_delta(self, fwd, strike, vol, currDate)

    def deltaHedgePL(self, vol, start_idx, end_idx):
        return _pyktlib.HistVolCalculator_deltaHedgePL(self, vol, start_idx, end_idx)

    def BreakevenVols(self):
        return _pyktlib.HistVolCalculator_BreakevenVols(self)

    def ts_(self):
        return _pyktlib.HistVolCalculator_ts_(self)

    def freq_(self):
        return _pyktlib.HistVolCalculator_freq_(self)

    def expiry_(self):
        return _pyktlib.HistVolCalculator_expiry_(self)

    def setExpiry(self, expiry):
        return _pyktlib.HistVolCalculator_setExpiry(self, expiry)

    def setFreq(self, freq):
        return _pyktlib.HistVolCalculator_setFreq(self, freq)

    def setTS(self, ts):
        return _pyktlib.HistVolCalculator_setTS(self, ts)
    __swig_destroy__ = _pyktlib.delete_HistVolCalculator
    __del__ = lambda self: None
HistVolCalculator_swigregister = _pyktlib.HistVolCalculator_swigregister
HistVolCalculator_swigregister(HistVolCalculator)

# This file is compatible with both classic and new-style classes.


