# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_pycmqlib')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_pycmqlib')
    _pycmqlib = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_pycmqlib', [dirname(__file__)])
        except ImportError:
            import _pycmqlib
            return _pycmqlib
        if fp is not None:
            try:
                _mod = imp.load_module('_pycmqlib', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _pycmqlib = swig_import_helper()
    del swig_import_helper
else:
    import _pycmqlib
del _swig_python_version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _pycmqlib.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _pycmqlib.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _pycmqlib.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _pycmqlib.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _pycmqlib.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _pycmqlib.SwigPyIterator_equal(self, x)

    def copy(self):
        return _pycmqlib.SwigPyIterator_copy(self)

    def next(self):
        return _pycmqlib.SwigPyIterator_next(self)

    def __next__(self):
        return _pycmqlib.SwigPyIterator___next__(self)

    def previous(self):
        return _pycmqlib.SwigPyIterator_previous(self)

    def advance(self, n):
        return _pycmqlib.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _pycmqlib.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _pycmqlib.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _pycmqlib.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _pycmqlib.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _pycmqlib.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _pycmqlib.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _pycmqlib.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)


def BlackPrice(F, K, vol, t_exp, df, PutCall):
    return _pycmqlib.BlackPrice(F, K, vol, t_exp, df, PutCall)
BlackPrice = _pycmqlib.BlackPrice

def BlackScholesPrice(S, K, vol, t_exp, rf, rd, PutCall):
    return _pycmqlib.BlackScholesPrice(S, K, vol, t_exp, rf, rd, PutCall)
BlackScholesPrice = _pycmqlib.BlackScholesPrice

def BlackDelta(F, K, vol, t_exp, df, PutCall):
    return _pycmqlib.BlackDelta(F, K, vol, t_exp, df, PutCall)
BlackDelta = _pycmqlib.BlackDelta

def BSDigitalPrice(F, K, vol, t_exp, df, PutCall):
    return _pycmqlib.BSDigitalPrice(F, K, vol, t_exp, df, PutCall)
BSDigitalPrice = _pycmqlib.BSDigitalPrice

def BachelierPrice(F, K, vol, t_exp, df, PutCall):
    return _pycmqlib.BachelierPrice(F, K, vol, t_exp, df, PutCall)
BachelierPrice = _pycmqlib.BachelierPrice

def BlackImpliedVol(MktPrice, F, K, r, T, PutCall, tol=1e-5):
    return _pycmqlib.BlackImpliedVol(MktPrice, F, K, r, T, PutCall, tol)
BlackImpliedVol = _pycmqlib.BlackImpliedVol

def BSImpliedVol(MktPrice, S, K, r, T, PutCall, tol=1e-5):
    return _pycmqlib.BSImpliedVol(MktPrice, S, K, r, T, PutCall, tol)
BSImpliedVol = _pycmqlib.BSImpliedVol

def BachelierImpliedVol(MktPrice, F, K, r, T, PutCall, tol=1e-5):
    return _pycmqlib.BachelierImpliedVol(MktPrice, F, K, r, T, PutCall, tol)
BachelierImpliedVol = _pycmqlib.BachelierImpliedVol

def american_prem_fut_btree(F, K, vol, t_exp, df, PutCall, bin_tree_nstep=128):
    return _pycmqlib.american_prem_fut_btree(F, K, vol, t_exp, df, PutCall, bin_tree_nstep)
american_prem_fut_btree = _pycmqlib.american_prem_fut_btree

def AmericanOptFutPrice(F, K, vol, t_exp, df, PutCall, bin_tree_nstep=128):
    return _pycmqlib.AmericanOptFutPrice(F, K, vol, t_exp, df, PutCall, bin_tree_nstep)
AmericanOptFutPrice = _pycmqlib.AmericanOptFutPrice

def AmericanImpliedVol(MktPrice, F, K, r, T, PutCall, tol=1e-5, bin_tree_nstep=128):
    return _pycmqlib.AmericanImpliedVol(MktPrice, F, K, r, T, PutCall, tol, bin_tree_nstep)
AmericanImpliedVol = _pycmqlib.AmericanImpliedVol

def SamuelsonFactor(a, b, t, T, mat):
    return _pycmqlib.SamuelsonFactor(a, b, t, T, mat)
SamuelsonFactor = _pycmqlib.SamuelsonFactor
class VolNode(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, VolNode, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, VolNode, name)
    __repr__ = _swig_repr

    def GetVolByStrike(self, strike, dmat=0):
        return _pycmqlib.VolNode_GetVolByStrike(self, strike, dmat)

    def GetVolByDelta(self, delta, dmat=0):
        return _pycmqlib.VolNode_GetVolByDelta(self, delta, dmat)

    def GetVolByMoneyness(self, ratio, dmat=0):
        return _pycmqlib.VolNode_GetVolByMoneyness(self, ratio, dmat)

    def GetInstVol(self, d=0):
        return _pycmqlib.VolNode_GetInstVol(self, d)

    def setAtm(self, atm):
        return _pycmqlib.VolNode_setAtm(self, atm)

    def setToday(self, dtoday):
        return _pycmqlib.VolNode_setToday(self, dtoday)

    def setExp(self, dexp):
        return _pycmqlib.VolNode_setExp(self, dexp)

    def setTime2Exp(self, expiryTimes):
        return _pycmqlib.VolNode_setTime2Exp(self, expiryTimes)

    def setAccrual(self, accrual):
        return _pycmqlib.VolNode_setAccrual(self, accrual)

    def atmVol_(self):
        return _pycmqlib.VolNode_atmVol_(self)

    def dtoday_(self):
        return _pycmqlib.VolNode_dtoday_(self)

    def dexp_(self):
        return _pycmqlib.VolNode_dexp_(self)

    def accrual_(self):
        return _pycmqlib.VolNode_accrual_(self)

    def expiry_(self):
        return _pycmqlib.VolNode_expiry_(self)

    def time2expiry_(self, dtoday, dexp):
        return _pycmqlib.VolNode_time2expiry_(self, dtoday, dexp)

    def nextwkday_(self, dtoday):
        return _pycmqlib.VolNode_nextwkday_(self, dtoday)

    def numBusDays_(self, dtoday, dexp):
        return _pycmqlib.VolNode_numBusDays_(self, dtoday, dexp)

    def getDayFraction_(self, dd):
        return _pycmqlib.VolNode_getDayFraction_(self, dd)

    def __init__(self, *args):
        this = _pycmqlib.new_VolNode(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pycmqlib.delete_VolNode
    __del__ = lambda self: None
VolNode_swigregister = _pycmqlib.VolNode_swigregister
VolNode_swigregister(VolNode)

class SamuelVolNode(VolNode):
    __swig_setmethods__ = {}
    for _s in [VolNode]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, SamuelVolNode, name, value)
    __swig_getmethods__ = {}
    for _s in [VolNode]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, SamuelVolNode, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _pycmqlib.new_SamuelVolNode(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def alpha_(self):
        return _pycmqlib.SamuelVolNode_alpha_(self)

    def beta_(self):
        return _pycmqlib.SamuelVolNode_beta_(self)

    def setAlpha(self, alpha):
        return _pycmqlib.SamuelVolNode_setAlpha(self, alpha)

    def setBeta(self, beta):
        return _pycmqlib.SamuelVolNode_setBeta(self, beta)

    def GetVolByMoneyness(self, ratio, dmat):
        return _pycmqlib.SamuelVolNode_GetVolByMoneyness(self, ratio, dmat)

    def GetInstVol(self, d):
        return _pycmqlib.SamuelVolNode_GetInstVol(self, d)
    __swig_destroy__ = _pycmqlib.delete_SamuelVolNode
    __del__ = lambda self: None
SamuelVolNode_swigregister = _pycmqlib.SamuelVolNode_swigregister
SamuelVolNode_swigregister(SamuelVolNode)

class Delta5VolNode(VolNode):
    __swig_setmethods__ = {}
    for _s in [VolNode]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Delta5VolNode, name, value)
    __swig_getmethods__ = {}
    for _s in [VolNode]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, Delta5VolNode, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _pycmqlib.new_Delta5VolNode(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _pycmqlib.delete_Delta5VolNode
    __del__ = lambda self: None

    def initialize(self):
        return _pycmqlib.Delta5VolNode_initialize(self)

    def setAtm(self, atm):
        return _pycmqlib.Delta5VolNode_setAtm(self, atm)

    def setFwd(self, fwd):
        return _pycmqlib.Delta5VolNode_setFwd(self, fwd)

    def setD10Vol(self, d10Vol):
        return _pycmqlib.Delta5VolNode_setD10Vol(self, d10Vol)

    def setD25Vol(self, d25Vol):
        return _pycmqlib.Delta5VolNode_setD25Vol(self, d25Vol)

    def setD75Vol(self, d75Vol):
        return _pycmqlib.Delta5VolNode_setD75Vol(self, d75Vol)

    def setD90Vol(self, d90Vol):
        return _pycmqlib.Delta5VolNode_setD90Vol(self, d90Vol)

    def d10Vol_(self):
        return _pycmqlib.Delta5VolNode_d10Vol_(self)

    def d25Vol_(self):
        return _pycmqlib.Delta5VolNode_d25Vol_(self)

    def d75Vol_(self):
        return _pycmqlib.Delta5VolNode_d75Vol_(self)

    def d90Vol_(self):
        return _pycmqlib.Delta5VolNode_d90Vol_(self)

    def fwd_(self):
        return _pycmqlib.Delta5VolNode_fwd_(self)

    def omega_(self):
        return _pycmqlib.Delta5VolNode_omega_(self)

    def GetVolByStrike(self, strike, t2mat=0):
        return _pycmqlib.Delta5VolNode_GetVolByStrike(self, strike, t2mat)

    def GetVolByDelta(self, delta, t2mat=0):
        return _pycmqlib.Delta5VolNode_GetVolByDelta(self, delta, t2mat)

    def GetVolByMoneyness(self, ratio, t2mat=0):
        return _pycmqlib.Delta5VolNode_GetVolByMoneyness(self, ratio, t2mat)
Delta5VolNode_swigregister = _pycmqlib.Delta5VolNode_swigregister
Delta5VolNode_swigregister(Delta5VolNode)

class SamuelDelta5VolNode(Delta5VolNode):
    __swig_setmethods__ = {}
    for _s in [Delta5VolNode]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, SamuelDelta5VolNode, name, value)
    __swig_getmethods__ = {}
    for _s in [Delta5VolNode]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, SamuelDelta5VolNode, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _pycmqlib.new_SamuelDelta5VolNode(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def alpha_(self):
        return _pycmqlib.SamuelDelta5VolNode_alpha_(self)

    def beta_(self):
        return _pycmqlib.SamuelDelta5VolNode_beta_(self)

    def setAlpha(self, alpha):
        return _pycmqlib.SamuelDelta5VolNode_setAlpha(self, alpha)

    def setBeta(self, beta):
        return _pycmqlib.SamuelDelta5VolNode_setBeta(self, beta)

    def GetVolByMoneyness(self, ratio, dmat):
        return _pycmqlib.SamuelDelta5VolNode_GetVolByMoneyness(self, ratio, dmat)

    def GetInstVol(self, d):
        return _pycmqlib.SamuelDelta5VolNode_GetInstVol(self, d)
    __swig_destroy__ = _pycmqlib.delete_SamuelDelta5VolNode
    __del__ = lambda self: None
SamuelDelta5VolNode_swigregister = _pycmqlib.SamuelDelta5VolNode_swigregister
SamuelDelta5VolNode_swigregister(SamuelDelta5VolNode)


def FitDelta5VolParams(t2exp, fwd, strikeList, volList):
    return _pycmqlib.FitDelta5VolParams(t2exp, fwd, strikeList, volList)
FitDelta5VolParams = _pycmqlib.FitDelta5VolParams
class Pricer(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Pricer, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Pricer, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

    def price(self):
        return _pycmqlib.Pricer_price(self)

    def delta(self):
        return _pycmqlib.Pricer_delta(self)

    def gamma(self):
        return _pycmqlib.Pricer_gamma(self)

    def vega(self):
        return _pycmqlib.Pricer_vega(self)

    def theta(self):
        return _pycmqlib.Pricer_theta(self)

    def setStrike(self, strike):
        return _pycmqlib.Pricer_setStrike(self, strike)

    def setFwd(self, fwd):
        return _pycmqlib.Pricer_setFwd(self, fwd)

    def setVol(self, vol):
        return _pycmqlib.Pricer_setVol(self, vol)

    def setIR(self, ir):
        return _pycmqlib.Pricer_setIR(self, ir)

    def setExpiry(self, dexp):
        return _pycmqlib.Pricer_setExpiry(self, dexp)

    def setT2Exp(self, time2expiry):
        return _pycmqlib.Pricer_setT2Exp(self, time2expiry)

    def setToday(self, dtoday):
        return _pycmqlib.Pricer_setToday(self, dtoday)

    def setOtype(self, otype):
        return _pycmqlib.Pricer_setOtype(self, otype)

    def strike_(self):
        return _pycmqlib.Pricer_strike_(self)

    def fwd_(self):
        return _pycmqlib.Pricer_fwd_(self)

    def vol_(self):
        return _pycmqlib.Pricer_vol_(self)

    def dexp_(self):
        return _pycmqlib.Pricer_dexp_(self)

    def dtoday_(self):
        return _pycmqlib.Pricer_dtoday_(self)

    def time2expiry_(self):
        return _pycmqlib.Pricer_time2expiry_(self)

    def irate_(self):
        return _pycmqlib.Pricer_irate_(self)

    def otype_(self):
        return _pycmqlib.Pricer_otype_(self)

    def priceTweak(self):
        return _pycmqlib.Pricer_priceTweak(self)

    def volTweak(self):
        return _pycmqlib.Pricer_volTweak(self)
    __swig_destroy__ = _pycmqlib.delete_Pricer
    __del__ = lambda self: None
Pricer_swigregister = _pycmqlib.Pricer_swigregister
Pricer_swigregister(Pricer)

class BlackPricer(Pricer):
    __swig_setmethods__ = {}
    for _s in [Pricer]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, BlackPricer, name, value)
    __swig_getmethods__ = {}
    for _s in [Pricer]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, BlackPricer, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _pycmqlib.new_BlackPricer(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def price(self):
        return _pycmqlib.BlackPricer_price(self)
    __swig_destroy__ = _pycmqlib.delete_BlackPricer
    __del__ = lambda self: None
BlackPricer_swigregister = _pycmqlib.BlackPricer_swigregister
BlackPricer_swigregister(BlackPricer)

class AmericanFutPricer(Pricer):
    __swig_setmethods__ = {}
    for _s in [Pricer]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, AmericanFutPricer, name, value)
    __swig_getmethods__ = {}
    for _s in [Pricer]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, AmericanFutPricer, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _pycmqlib.new_AmericanFutPricer(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def price(self):
        return _pycmqlib.AmericanFutPricer_price(self)
    __swig_destroy__ = _pycmqlib.delete_AmericanFutPricer
    __del__ = lambda self: None
AmericanFutPricer_swigregister = _pycmqlib.AmericanFutPricer_swigregister
AmericanFutPricer_swigregister(AmericanFutPricer)

class DigitalPricer(Pricer):
    __swig_setmethods__ = {}
    for _s in [Pricer]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, DigitalPricer, name, value)
    __swig_getmethods__ = {}
    for _s in [Pricer]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, DigitalPricer, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _pycmqlib.new_DigitalPricer(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def price(self):
        return _pycmqlib.DigitalPricer_price(self)
    __swig_destroy__ = _pycmqlib.delete_DigitalPricer
    __del__ = lambda self: None
DigitalPricer_swigregister = _pycmqlib.DigitalPricer_swigregister
DigitalPricer_swigregister(DigitalPricer)

class BachelierPricer(Pricer):
    __swig_setmethods__ = {}
    for _s in [Pricer]:
        __swig_setmethods__.update(getattr(_s, '__swig_setmethods__', {}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, BachelierPricer, name, value)
    __swig_getmethods__ = {}
    for _s in [Pricer]:
        __swig_getmethods__.update(getattr(_s, '__swig_getmethods__', {}))
    __getattr__ = lambda self, name: _swig_getattr(self, BachelierPricer, name)
    __repr__ = _swig_repr

    def __init__(self, *args):
        this = _pycmqlib.new_BachelierPricer(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def price(self):
        return _pycmqlib.BachelierPricer_price(self)
    __swig_destroy__ = _pycmqlib.delete_BachelierPricer
    __del__ = lambda self: None
BachelierPricer_swigregister = _pycmqlib.BachelierPricer_swigregister
BachelierPricer_swigregister(BachelierPricer)

class TimeSeries(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TimeSeries, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TimeSeries, name)
    __repr__ = _swig_repr

    def date_(self):
        return _pycmqlib.TimeSeries_date_(self)

    def data_(self):
        return _pycmqlib.TimeSeries_data_(self)

    def __init__(self, *args):
        this = _pycmqlib.new_TimeSeries(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def setDate(self, date):
        return _pycmqlib.TimeSeries_setDate(self, date)

    def setData(self, data):
        return _pycmqlib.TimeSeries_setData(self, data)

    def isValidated(self):
        return _pycmqlib.TimeSeries_isValidated(self)
    __swig_destroy__ = _pycmqlib.delete_TimeSeries
    __del__ = lambda self: None
TimeSeries_swigregister = _pycmqlib.TimeSeries_swigregister
TimeSeries_swigregister(TimeSeries)


def GetTSWeightedSum(ts1, ts2, w1, w2):
    return _pycmqlib.GetTSWeightedSum(ts1, ts2, w1, w2)
GetTSWeightedSum = _pycmqlib.GetTSWeightedSum
class HistVolCalculator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, HistVolCalculator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, HistVolCalculator, name)
    __repr__ = _swig_repr

    def __init__(self, ts, expiry, freq, btMonths):
        this = _pycmqlib.new_HistVolCalculator(ts, expiry, freq, btMonths)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def pricer(self, fwd, strike, vol, currDate):
        return _pycmqlib.HistVolCalculator_pricer(self, fwd, strike, vol, currDate)

    def delta(self, fwd, strike, vol, currDate):
        return _pycmqlib.HistVolCalculator_delta(self, fwd, strike, vol, currDate)

    def deltaHedgePL(self, vol, start_idx, end_idx):
        return _pycmqlib.HistVolCalculator_deltaHedgePL(self, vol, start_idx, end_idx)

    def BreakevenVols(self):
        return _pycmqlib.HistVolCalculator_BreakevenVols(self)

    def ts_(self):
        return _pycmqlib.HistVolCalculator_ts_(self)

    def freq_(self):
        return _pycmqlib.HistVolCalculator_freq_(self)

    def expiry_(self):
        return _pycmqlib.HistVolCalculator_expiry_(self)

    def setExpiry(self, expiry):
        return _pycmqlib.HistVolCalculator_setExpiry(self, expiry)

    def setFreq(self, freq):
        return _pycmqlib.HistVolCalculator_setFreq(self, freq)

    def setTS(self, ts):
        return _pycmqlib.HistVolCalculator_setTS(self, ts)
    __swig_destroy__ = _pycmqlib.delete_HistVolCalculator
    __del__ = lambda self: None
HistVolCalculator_swigregister = _pycmqlib.HistVolCalculator_swigregister
HistVolCalculator_swigregister(HistVolCalculator)

class IntVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, IntVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, IntVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _pycmqlib.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pycmqlib.IntVector___nonzero__(self)

    def __bool__(self):
        return _pycmqlib.IntVector___bool__(self)

    def __len__(self):
        return _pycmqlib.IntVector___len__(self)

    def __getslice__(self, i, j):
        return _pycmqlib.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pycmqlib.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pycmqlib.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pycmqlib.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pycmqlib.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pycmqlib.IntVector___setitem__(self, *args)

    def pop(self):
        return _pycmqlib.IntVector_pop(self)

    def append(self, x):
        return _pycmqlib.IntVector_append(self, x)

    def empty(self):
        return _pycmqlib.IntVector_empty(self)

    def size(self):
        return _pycmqlib.IntVector_size(self)

    def swap(self, v):
        return _pycmqlib.IntVector_swap(self, v)

    def begin(self):
        return _pycmqlib.IntVector_begin(self)

    def end(self):
        return _pycmqlib.IntVector_end(self)

    def rbegin(self):
        return _pycmqlib.IntVector_rbegin(self)

    def rend(self):
        return _pycmqlib.IntVector_rend(self)

    def clear(self):
        return _pycmqlib.IntVector_clear(self)

    def get_allocator(self):
        return _pycmqlib.IntVector_get_allocator(self)

    def pop_back(self):
        return _pycmqlib.IntVector_pop_back(self)

    def erase(self, *args):
        return _pycmqlib.IntVector_erase(self, *args)

    def __init__(self, *args):
        this = _pycmqlib.new_IntVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _pycmqlib.IntVector_push_back(self, x)

    def front(self):
        return _pycmqlib.IntVector_front(self)

    def back(self):
        return _pycmqlib.IntVector_back(self)

    def assign(self, n, x):
        return _pycmqlib.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _pycmqlib.IntVector_resize(self, *args)

    def insert(self, *args):
        return _pycmqlib.IntVector_insert(self, *args)

    def reserve(self, n):
        return _pycmqlib.IntVector_reserve(self, n)

    def capacity(self):
        return _pycmqlib.IntVector_capacity(self)
    __swig_destroy__ = _pycmqlib.delete_IntVector
    __del__ = lambda self: None
IntVector_swigregister = _pycmqlib.IntVector_swigregister
IntVector_swigregister(IntVector)

class DblVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, DblVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, DblVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _pycmqlib.DblVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pycmqlib.DblVector___nonzero__(self)

    def __bool__(self):
        return _pycmqlib.DblVector___bool__(self)

    def __len__(self):
        return _pycmqlib.DblVector___len__(self)

    def __getslice__(self, i, j):
        return _pycmqlib.DblVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pycmqlib.DblVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pycmqlib.DblVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pycmqlib.DblVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pycmqlib.DblVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pycmqlib.DblVector___setitem__(self, *args)

    def pop(self):
        return _pycmqlib.DblVector_pop(self)

    def append(self, x):
        return _pycmqlib.DblVector_append(self, x)

    def empty(self):
        return _pycmqlib.DblVector_empty(self)

    def size(self):
        return _pycmqlib.DblVector_size(self)

    def swap(self, v):
        return _pycmqlib.DblVector_swap(self, v)

    def begin(self):
        return _pycmqlib.DblVector_begin(self)

    def end(self):
        return _pycmqlib.DblVector_end(self)

    def rbegin(self):
        return _pycmqlib.DblVector_rbegin(self)

    def rend(self):
        return _pycmqlib.DblVector_rend(self)

    def clear(self):
        return _pycmqlib.DblVector_clear(self)

    def get_allocator(self):
        return _pycmqlib.DblVector_get_allocator(self)

    def pop_back(self):
        return _pycmqlib.DblVector_pop_back(self)

    def erase(self, *args):
        return _pycmqlib.DblVector_erase(self, *args)

    def __init__(self, *args):
        this = _pycmqlib.new_DblVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _pycmqlib.DblVector_push_back(self, x)

    def front(self):
        return _pycmqlib.DblVector_front(self)

    def back(self):
        return _pycmqlib.DblVector_back(self)

    def assign(self, n, x):
        return _pycmqlib.DblVector_assign(self, n, x)

    def resize(self, *args):
        return _pycmqlib.DblVector_resize(self, *args)

    def insert(self, *args):
        return _pycmqlib.DblVector_insert(self, *args)

    def reserve(self, n):
        return _pycmqlib.DblVector_reserve(self, n)

    def capacity(self):
        return _pycmqlib.DblVector_capacity(self)
    __swig_destroy__ = _pycmqlib.delete_DblVector
    __del__ = lambda self: None
DblVector_swigregister = _pycmqlib.DblVector_swigregister
DblVector_swigregister(DblVector)

class StringVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, StringVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, StringVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _pycmqlib.StringVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pycmqlib.StringVector___nonzero__(self)

    def __bool__(self):
        return _pycmqlib.StringVector___bool__(self)

    def __len__(self):
        return _pycmqlib.StringVector___len__(self)

    def __getslice__(self, i, j):
        return _pycmqlib.StringVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pycmqlib.StringVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pycmqlib.StringVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pycmqlib.StringVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pycmqlib.StringVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pycmqlib.StringVector___setitem__(self, *args)

    def pop(self):
        return _pycmqlib.StringVector_pop(self)

    def append(self, x):
        return _pycmqlib.StringVector_append(self, x)

    def empty(self):
        return _pycmqlib.StringVector_empty(self)

    def size(self):
        return _pycmqlib.StringVector_size(self)

    def swap(self, v):
        return _pycmqlib.StringVector_swap(self, v)

    def begin(self):
        return _pycmqlib.StringVector_begin(self)

    def end(self):
        return _pycmqlib.StringVector_end(self)

    def rbegin(self):
        return _pycmqlib.StringVector_rbegin(self)

    def rend(self):
        return _pycmqlib.StringVector_rend(self)

    def clear(self):
        return _pycmqlib.StringVector_clear(self)

    def get_allocator(self):
        return _pycmqlib.StringVector_get_allocator(self)

    def pop_back(self):
        return _pycmqlib.StringVector_pop_back(self)

    def erase(self, *args):
        return _pycmqlib.StringVector_erase(self, *args)

    def __init__(self, *args):
        this = _pycmqlib.new_StringVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _pycmqlib.StringVector_push_back(self, x)

    def front(self):
        return _pycmqlib.StringVector_front(self)

    def back(self):
        return _pycmqlib.StringVector_back(self)

    def assign(self, n, x):
        return _pycmqlib.StringVector_assign(self, n, x)

    def resize(self, *args):
        return _pycmqlib.StringVector_resize(self, *args)

    def insert(self, *args):
        return _pycmqlib.StringVector_insert(self, *args)

    def reserve(self, n):
        return _pycmqlib.StringVector_reserve(self, n)

    def capacity(self):
        return _pycmqlib.StringVector_capacity(self)
    __swig_destroy__ = _pycmqlib.delete_StringVector
    __del__ = lambda self: None
StringVector_swigregister = _pycmqlib.StringVector_swigregister
StringVector_swigregister(StringVector)

class ConstCharVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, ConstCharVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ConstCharVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _pycmqlib.ConstCharVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _pycmqlib.ConstCharVector___nonzero__(self)

    def __bool__(self):
        return _pycmqlib.ConstCharVector___bool__(self)

    def __len__(self):
        return _pycmqlib.ConstCharVector___len__(self)

    def __getslice__(self, i, j):
        return _pycmqlib.ConstCharVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _pycmqlib.ConstCharVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _pycmqlib.ConstCharVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _pycmqlib.ConstCharVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _pycmqlib.ConstCharVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _pycmqlib.ConstCharVector___setitem__(self, *args)

    def pop(self):
        return _pycmqlib.ConstCharVector_pop(self)

    def append(self, x):
        return _pycmqlib.ConstCharVector_append(self, x)

    def empty(self):
        return _pycmqlib.ConstCharVector_empty(self)

    def size(self):
        return _pycmqlib.ConstCharVector_size(self)

    def swap(self, v):
        return _pycmqlib.ConstCharVector_swap(self, v)

    def begin(self):
        return _pycmqlib.ConstCharVector_begin(self)

    def end(self):
        return _pycmqlib.ConstCharVector_end(self)

    def rbegin(self):
        return _pycmqlib.ConstCharVector_rbegin(self)

    def rend(self):
        return _pycmqlib.ConstCharVector_rend(self)

    def clear(self):
        return _pycmqlib.ConstCharVector_clear(self)

    def get_allocator(self):
        return _pycmqlib.ConstCharVector_get_allocator(self)

    def pop_back(self):
        return _pycmqlib.ConstCharVector_pop_back(self)

    def erase(self, *args):
        return _pycmqlib.ConstCharVector_erase(self, *args)

    def __init__(self, *args):
        this = _pycmqlib.new_ConstCharVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _pycmqlib.ConstCharVector_push_back(self, x)

    def front(self):
        return _pycmqlib.ConstCharVector_front(self)

    def back(self):
        return _pycmqlib.ConstCharVector_back(self)

    def assign(self, n, x):
        return _pycmqlib.ConstCharVector_assign(self, n, x)

    def resize(self, *args):
        return _pycmqlib.ConstCharVector_resize(self, *args)

    def insert(self, *args):
        return _pycmqlib.ConstCharVector_insert(self, *args)

    def reserve(self, n):
        return _pycmqlib.ConstCharVector_reserve(self, n)

    def capacity(self):
        return _pycmqlib.ConstCharVector_capacity(self)
    __swig_destroy__ = _pycmqlib.delete_ConstCharVector
    __del__ = lambda self: None
ConstCharVector_swigregister = _pycmqlib.ConstCharVector_swigregister
ConstCharVector_swigregister(ConstCharVector)

# This file is compatible with both classic and new-style classes.


